name: meswan
favicon: null
layout_spectrum: 0.5853823069483042
typography_spectrum: 0.41971738706342876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5008376403711736
  lightness: 0.9717369177378714
  saturation: 0.3478995894547552
  rhythmicContrast: 0.6362662941683084
purpose: []
